# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flight_scheduler.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
  name='flight_scheduler.proto',
  package='flightscheduler',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16\x66light_scheduler.proto\x12\x10\x66lightscheduler"\x1c\n\x13ScheduleFlightRequest\x12\x05\n\x01\x62\x18\n\x14ScheduleFlightResponse\x12\x0e\n\x06\x63onfirm\x18\x01 \x01(\t2\x85\x01\n\x10\x46lightScheduler\x12G\n\rScheduleFlight\x12\x10\x66lightscheduler.ScheduleFlightRequest\x1a\x14\x66lightscheduler.ScheduleFlightResponseb\x06proto3')
)


# Enums
_FLIGHTSTATUS = _descriptor.EnumDescriptor(
  name='FlightStatus',
  full_name='flightscheduler.FlightStatus',
  values=[
    _descriptor.EnumValueDescriptor(
      name='SCHEDULED', index=0, number=0,
      serialized_options=None, type=None),
    _descriptor.EnumValueDescriptor(
      name='IN_PROGRESS', index=1, number=1,
      serialized_options=None, type=None),
    _descriptor.EnumValueDescriptor(
      name='COMPLETED', index=2, number=2,
      serialized_options=None, type=None),
    _descriptor.EnumValueDescriptor(
      name='CANCELLED', index=3, number=3,
      serialized_options=None, type=None),
  ],
  containing_type=None,
  serialized_options=None,
)

# Other messages
class ScheduleFlightRequest(_message.Message, metaclass=_reflection.GeneratedProtocolMessageType):
    DESCRIPTOR = _descriptor.Descriptor(
        name='ScheduleFlightRequest',
        full_name='flightscheduler.ScheduleFlightRequest',
        filename=None,
        file=DESCRIPTOR,
        containing_type=None,
        fields=[
            _descriptor.FieldDescriptor(
                name='pilot_id', full_name='flightscheduler.ScheduleFlightRequest.pilot_id', index=0,
                number=1, type=9, cpp_type=9, label=1,
                has_default_value=False, default_value=_b("").decode('utf-8'),
                message_type=None, enum_type=None,
                containing_type=None, is_extension=False,
                serialized_options=None, file=DESCRIPTOR),
            _descriptor.FieldDescriptor(
                name='flight_date', full_name='flightscheduler.ScheduleFlightRequest.flight_date', index=1,
                number=2, type=9, cpp_type=9, label=1,
                has_default_value=False, default_value=_b("").decode('utf-8'),
                message_type=None, enum_type=None,
                containing_type=None, is_extension=False,
                serialized_options=None, file=DESCRIPTOR),
        ],
        extensions=[],
        nested_types=[],
        enum_types=[],
        serialized_options=None,
    )

class ScheduleFlightResponse(_message.Message, metaclass=_reflection.GeneratedProtocolMessageType):
    DESCRIPTOR = _descriptor.Descriptor(
        name='ScheduleFlightResponse',
        full_name='flightscheduler.ScheduleFlightResponse',
        filename=None,
        file=DESCRIPTOR,
        containing_type=None,
        fields=[
            _descriptor.FieldDescriptor(
                name='confirmation_message', full_name='flightscheduler.ScheduleFlightResponse.confirmation_message', index=0,
                number=1, type=9, cpp_type=9, label=1,
                has_default_value=False, default_value=_b("").decode('utf-8'),
                message_type=None, enum_type=None,
                containing_type=None, is_extension=False,
                serialized_options=None, file=DESCRIPTOR),
        ],
        extensions=[],
        nested_types=[],
        enum_types=[],
        serialized_options=None,
    )

_sym_db.RegisterMessage(ScheduleFlightRequest)
_sym_db.RegisterMessage(ScheduleFlightResponse)
